### ISSUE TITLE
Add class syntax

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#124]
Add class definition syntax. Specifically, add `Class` and `Inherit` functions and method definition syntax. Please refer to the documentation for details of each.

# TODOs:

- [x] Add the method definition node to `AST` (https://github.com/erg-lang/erg/commit/924ab27369051b6791f41dd747acc29c2f236d59)
- [x] Add `Class` function (https://github.com/erg-lang/erg/commit/cf0858ddde9f022bacafd911b3ac7be18614e6ba)
- [x] Add `Inherit` function (https://github.com/erg-lang/erg/commit/cf0858ddde9f022bacafd911b3ac7be18614e6ba)
- [x] Implement method definition check
  - [x] type check
  - [x] side effect check
  - [x] ownership check
- [ ] Implement derivative features of class
  - [ ] `Inheritable`
- [x] Implement method definition code generating
