### ISSUE TITLE
Implement `Dict` literal

### ISSUE THREAD

**Issue by mtshiba** [erg-lang/erg#194]
Related to #35.

# TODOs:

- [x] Completed implement normal dict
    - [x] parse
    - [x] hir
    - [x]  lower
        - [x] add Dict/Dict! type
        - [x] register `Dict`, `Dict!` definitions to the builtin `Context`
        - [x] check if objects implement `Eq`
        - [ ] (optional) warn of any duplicate elements
        - [x] tyvar
        - [x] link
    - [x] effectcheck
    - [x] memcheck
    - [x] codegen

**Comment by mtshiba** [comment]
Fixed by #204.
